### ISSUE TITLE
Stopped working at some point

### ISSUE THREAD

**Issue by peterlauri** [SamEdwardes/alfred-workflow-toggle-stage-manager#2]
The action does not work anymore. If I enter to MacOS Settings and toggle Stage Manager once it starts working. After closing MacOS settings application it stops working again.

```
[08:53:44.160] Toggle Stage Manager[Keyword] Processing complete
[08:53:44.169] Toggle Stage Manager[Keyword] Passing output '' to Run Script
```

However, it doesn't look to be a problem with your action, because if I set the values manually it doesn't work either.

```
# defaults write com.apple.WindowManager GloballyEnabled -bool true
# defaults read com.apple.WindowManager GloballyEnabled
1
# defaults write com.apple.WindowManager GloballyEnabled -bool false
# defaults read com.apple.WindowManager GloballyEnabled
0
```

Might there be some way to reset stage manager to get back working?

**Comment by peterlauri** [comment]
Upgraded MacOS and it started to work as before :)

**Comment by SamEdwardes** [comment]
Thanks for the issue! Happy to to hear that the update solved it :)
